### ISSUE TITLE
Fix error when creating 1st tag

### ISSUE THREAD

**Issue by pranaysahith** [k8-proxy/auto-tagging#13]
1. When the auto-tagging workflow runs for the first time, `repo_name` variable will be empty in `tagging` step which causes error in `label_PR_and_Issues` step.
2. Add authorization bearer token in header to all API calls so that the workflow will work for private repos as well.

**Comment by samarthdd** [comment]
this is fixed

**Comment by samarthdd** [comment]
in pr https://github.com/k8-proxy/auto-tagging/pull/14
